imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets:
        version_strategy: irozgar_gulp_rev_versions.asset.gulp_rev_version_strategy
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

assetic:
    write_to: '%kernel.root_dir%/../web/static/orig'
    filters:
        cssrewrite: ~
        compass:
            bin: /usr/local/bin/compass
            load_paths: 
            - "%kernel.root_dir%/../src/AppBundle/Resources/private/bower/"
        uglifycss:
            bin: /usr/local/bin/uglifycss
        uglifyjs2:
            bin: /usr/local/bin/uglifyjs
irozgar_gulp_rev_versions:
    manifest_path: "../src/AppBundle/Resources/assets/rev-manifest.json"

sonata_seo:
    encoding:         UTF-8
    page:
        title:        Website Name
        default:      sonata.seo.page.default
        metas:
            name:
                robots:               index, follow                
                description:          The description
                viewport:             width=device-width,height=device-height,initial-scale=1,maximum-scale=1,minimum-scale=1

                # Only if an application
                #application-name:     Website Name

                # Android
                #mobile-web-app-capable: 'yes'
                theme-color:            '#000'

                # Apple App Capable
                #apple-mobile-web-app-capable:           'yes'
                #apple-mobile-web-app-status-bar-style:  'black-translucent'

                # Windows Phone - Back/Forward Button Colour
                msapplication-navbutton-color:          '#000'

                # Windows Phone - Shortcut Tile Colour
                msapplication-TileColor:                '#000'

            property:
                # Facebook application settings - will be auto-added by fb ask if used
                #fb:app_id:          XXXXXX
                #fb:admins:          admin1, admin2

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                og:site_name:       Website Name
                og:description:     A demo of the some rich bundles for your Symfony2 projects
                og:locale:          en_GB

                #web based options: website, article or blog
                og:type:            website

            http-equiv:
                'Content-Type':         text/html; charset=utf-8
                #'X-Ua-Compatible':      IE=EmulateIE7

            charset:
                UTF-8:    ''

        head:
            xmlns:          http://www.w3.org/1999/xhtml
            xmlns:og:       http://opengraphprotocol.org/schema/
            #xmlns:fb:      "http://www.facebook.com/2008/fbml"

            #Possible twitter namespace??
            #xmlns:twitter: "http://api.twitter.com/"
bw_base:
    page:
        #Will be merged with Sonata meta tags when being fetched using Twig extension - defining here means will auto-detect tags which are image assets and pass through the default package's getURL method (e.g. for CDN prefix in live environment)
        metas:
            name:
                # Twitter card settings
                twitter:card:       'summary_large_image'
                twitter:site:       '@silverbackis'
                twitter:creator:    '@silverbackis'
                #twitter:image:      '%ogimages_folder%SocialImage.png'
                twitter:image:alt:  'Alt tag for the twigger image'

                #msapplication-TileImage:            '%icons_folder%mstile-144x144.png'
                #msapplication-square70x70logo:      '%icons_folder%mstile-70x70.png'
                #msapplication-square150x150logo:    '%icons_folder%mstile-150x150logo.png'
                #msapplication-square310x310logo:    '%icons_folder%mstile-310x310.png'
                #msapplication-wide310x150logo:      '%icons_folder%mstile-310x150.png'
            property:
                #Repeat images tags as many times as you want for new images
                #og:image:          '%ogimages_folder%SocialImage.png'
                #og:image:width:    '500'
                #og:image:height:   '500'
        links:
            rel:
                apple-touch-icon-precomposed:
                    #- { sizes: 57x57, href: '%icons_folder%apple-touch-icon-57x57.png' }
                    #- { sizes: 114x114, href: '%icons_folder%apple-touch-icon-114x114.png' }
                    #- { sizes: 72x72, href: '%icons_folder%apple-touch-icon-72x72.png' }
                    #- { sizes: 144x144, href: '%icons_folder%apple-touch-icon-144x144.png' }
                    #- { sizes: 60x60, href: '%icons_folder%apple-touch-icon-60x60.png' }
                    #- { sizes: 120x120, href: '%icons_folder%apple-touch-icon-120x120.png' }
                    #- { sizes: 76x76, href: '%icons_folder%apple-touch-icon-76x76.png' }
                    #- { sizes: 152x152, href: '%icons_folder%apple-touch-icon-152x152.png' }
                icon:
                    #- { type: image/png, sizes: 196x196, href: '%icons_folder%favicon-196x196.png' }
                    #- { type: image/png, sizes: 96x96, href: '%icons_folder%favicon-96x96.png' }
                    #- { type: image/png, sizes: 32x32, href: '%icons_folder%favicon-32x32.png' }
                    #- { type: image/png, sizes: 16x16, href: '%icons_folder%favicon-16x16.png' }
                    #- { type: image/png, sizes: 128x128, href: '%icons_folder%favicon-128x128.png' }
                    #- { type: image/x-icon, href: '%icons_folder%favicon.ico' }
        js_sdk:
            ganalytics:
                enabled: false
                id: null
                domain: auto
            woopra:
                enabled: false
                domain: null
            facebookPixel:
                enabled: false
                id: null
            facebook:
                enabled: false
                app_id: null
                xfbml: true
                version: 'v2.8'
                language: en_US
                login_status_check: false
                debug: false
            twitter: false