# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    contact_type:
        class: AppBundle\Form\ContactType
        arguments: ["@translator"]
        tags:
            - { name: form.type }
